server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/bpgc/springcloud-config-repo.git
          username: baopoguicai
          password: 19935y4r
          search-paths: common-config,gateway-config,key-generator-config,stock-service-config,trade-service-config,user-service-config
#      discovery:
#        enabled: true
#        service-id: config-server
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          # kafka的消息中间件服务器
          brokers: 127.0.0.1:2181 # 固定
          # zookeeper的节点，若集群，后面加，号隔开
          zk-nodes: 127.0.0.1:5181 #固定
          # 若设置为false，就不会自动创建topic，有可能你Topic还没创建就直接调用
          auto-create-topics: true

management:
  security:
    enabled: false # 若为false，暴露所有端点
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/,http://127.0.0.1:8889/eureka/ #固定
  instance:
    ip-address: 123.207.71.165 #配置中心部署机器,公网ip,固定
    prefer-ip-address: true #优先选用ip-address


