server:
  port: 8811
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/bpgc/springcloud-config-repo.git
          username: baopoguicai
          password: 19935y4r
          search-paths: common-config,gateway-config,key-generator-config,stock-service-config,trade-service-config,user-service-config
#      discovery:
#        enabled: true
#        service-id: config-server
    bus:
      trace:
        enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        #这里用stream给我们提供的默认output，后面会讲到自定义output
        output:
        # 消息发往目的地
          destination: stream-demo
        #消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: text/plain
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/,http://127.0.0.1:8889/eureka/


