server:
  port: 8888
eureka:
  instance:
    hostname: eureka_1 #eureka集群中唯一标志
  client:
    service-url: #指定服务注册中心地址,类型为 HashMap
      defaultZone: http://127.0.0.1:8888/eureka/
    fetch-registry: false #启动尝试拉取已经注册服务列表,目前自己是第一个，不拉取
    register-with-eureka: true  #注册中心本身也是服务，需要不需要向自己注册，启动尝试向其他服务注册自己,到时候部署2台，所以true
  server:
    enable-self-preservation: false
spring:
  application:
    name: service-registry
